title: Axis of Stevil
email: stevenmaguire@gmail.com
description: "Axis of Stevil - It's the Beginning of Stevilization"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.axisofstevil.com" # the base hostname & protocol for your site
enforce_ssl: www.axisofstevil.com
content_baseurl: "https://axisofstevil.s3.amazonaws.com"
service_url: "https://service.axisofstevil.com"
twitter_username: AxisofStevil
github_username:  axisofstevil
keywords: "Axis of Stevil, Dinosaur, Pop, Accountant, Axis, Stevil, Steven, Art"
random_enabled: true
paginate: 20
paginate_path: "/page/:num"
sass:
    style: compressed
exclude:
    - bower.json
    - bower_components
    - Gemfile
    - Gemfile.lock
    - gulpfile.js
    - package.json
    - node_modules
    - Rakefile
    - README.md
safe: false
navigation:
    categories:
        - slug: 'publications'
          label: 'Words and pictures'
        - slug: 'language'
          label: 'Vocabulary'
        - slug: 'featured-steves'
          label: 'People'
        - slug: 'ask-stevil'
          label: 'AMA'
    pages:
        - slug: 'mission'
          label: 'Mission'
        - slug: 'history'
          label: 'History'
        - slug: 'shirts'
          label: 'Shirts'
collections:
    collections:
      output: true
    history:
array: []

# Build settings
markdown: kramdown
#kramdown:
#  parse_block_html: true

gems: ['nokogiri','octopress-minify-html','jekyll-redirect-from','jekyll-paginate']

default_quote: "Random instanity at its finest."
default_hero_image_css: "background-image: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4IiBoZWlnaHQ9IjgiPjxwYXRoIGQ9Ik0tMiAxMEwxMCAtMlpNMTAgNkw2IDEwWk0tMiAyTDIgLTIiIHN0cm9rZT0iIzIyMiIgc3Ryb2tlLXdpZHRoPSI0LjUiPjwvcGF0aD4KPC9zdmc+'),url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiPgo8bGluZWFyR3JhZGllbnQgaWQ9ImciIHgyPSIxIiB5Mj0iMSI+CjxzdG9wIHN0b3AtY29sb3I9IiNGMTkiPjwvc3RvcD4KPHN0b3Agb2Zmc2V0PSIxMDAlIiBzdG9wLWNvbG9yPSIjMENGIj48L3N0b3A+CjwvbGluZWFyR3JhZGllbnQ+CjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZykiPjwvcmVjdD4KPC9zdmc+'); background-repeat: inherit; background-size: auto;"

# Service settings
algolia:
    app_id: 0O6JQYRQU7
    search_key: ac9af9df8e0e60f4352bbb10bdc18032
